# Generated by Django 4.2.6 on 2023-10-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
