# Generated by Django 4.2.6 on 2023-10-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_nayaqn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nayaqn',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
