# Generated by Django 4.2.6 on 2023-10-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_nayaqn_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('option1', models.TextField(max_length=100)),
                ('option2', models.TextField(max_length=100)),
                ('option3', models.TextField(max_length=100)),
                ('option4', models.TextField(max_length=100)),
                ('ans', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
