# Generated by Django 4.2.6 on 2023-10-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_question_delete_contact1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
